Fix date typing issue
Follow-up for a bug introduced in #23 that caused last night's forecast jobs
to fail in Airflow with:

```
AttributeError: Can only use .dt accessor with datetimelike values
```